"""remove_selected_answer_field

Revision ID: 377c0fa12420
Revises: 8b44c00e1d60
Create Date: 2025-06-02 12:35:12.649766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377c0fa12420'
down_revision: Union[str, None] = '8b44c00e1d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answers', 'selected_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('selected_answer', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
