"""Add word and translation answer fields to user_answers

Revision ID: 8b44c00e1d60
Revises: 
Create Date: 2025-06-02 12:31:51.780182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b44c00e1d60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('selected_word_answer', sa.Text(), nullable=True, comment='用户选择的单词答案'))
    op.add_column('user_answers', sa.Column('selected_translation_answer', sa.Text(), nullable=True, comment='用户选择的翻译答案'))
    # Note: Skipping UUID type changes as SQLite doesn't support ALTER COLUMN TYPE
    # The existing database already has the correct UUID types
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answers', 'selected_translation_answer')
    op.drop_column('user_answers', 'selected_word_answer')
    # ### end Alembic commands ###
